### ISSUE TITLE
Lease isn't deleted after unknown ERROR

### ISSUE THREAD

**Issue by M-J-Brown** [jchapuis/leases4s#52]
After receiving an unknown error, the lease becomes stuck indefinitely, until my service is restarted, which THEN triggers lease cleanup. This went on for 15 hours until I noticed and restarted the service.

(sorry about the bottom-to-top logs)
```
Nov 05 18:18:15.498
Failed to acquire lease my-lease for 540bfd56-3d0f-4d08-8e1e-72ee8a12d126: Failed to create lease my-lease for 540bfd56-3d0f-4d08-8e1e-72ee8a12d126, retrying...

Nov 05 18:18:15.497
Failed to create lease my-lease for 540bfd56-3d0f-4d08-8e1e-72ee8a12d126: Conflict

Nov 05 18:18:15.438
Attempting to create lease my-lease for 540bfd56-3d0f-4d08-8e1e-72ee8a12d126

Nov 05 18:18:12.436
Failed to acquire lease my-lease for 540bfd56-3d0f-4d08-8e1e-72ee8a12d126: Failed to create lease my-lease for 540bfd56-3d0f-4d08-8e1e-72ee8a12d126, retrying...

Nov 05 18:18:12.391
Failed to create lease my-lease for 540bfd56-3d0f-4d08-8e1e-72ee8a12d126: Conflict

Nov 05 18:18:12.276
Attempting to create lease my-lease for 540bfd56-3d0f-4d08-8e1e-72ee8a12d126

Nov 05 17:53:07.981
Received event for unknown: "ERROR"

Nov 05 17:53:07.888
Received event for unknown: "ERROR"

Nov 05 17:53:07.836
Successfully created lease my-lease for f26187fc-33ba-46ae-9e0e-8ff8656c86e6

Nov 05 17:53:07.826
Refreshing watcher subscription from revision 1890751571 (trigger: Timed out waiting for pull after 30 seconds)

Nov 05 17:53:07.823
Refreshing watcher subscription from revision 1890751571 (trigger: Timed out waiting for pull after 30 seconds)

Nov 05 17:53:07.547
Attempting to create lease my-lease for f26187fc-33ba-46ae-9e0e-8ff8656c86e6
```

I'm not sure if this is something up with how I'm sewing the lease into my application, or an issue with the library.

In `Main.scala` I have:
```

    for {
      implicit0(logger: Logger[IO])           <- Resource.eval(loggerFactory.fromName("K8sLease"))
      kubeConfig                              <- Resource.eval(KubeConfig.cluster[IO])
      implicit0(client: KubernetesClient[IO]) <- KubernetesClient[IO](kubeConfig)
      implicit0(namespace: Namespace)          = Namespace(config.namespace)
      repo                                    <- LeaseRepository.kubernetes[IO](Label(ks"app", ks"my-service"))
      leaseFn                                  = (holder: HolderID) => repo.acquire(LeaseID(ks"my-lease"), holder)
    } yield leaseFn

```
I'm passing the lease around as: `leaseObtainFn: HolderID => Resource[IO, HeldLease[IO]]`

Then using it as
```
supervisor.supervise {
          leaseObtainFn(HolderID.unique)
            .use(_.guard { ??? } )
          }
```

**Comment by jchapuis** [comment]
@M-J-Brown sorry about this, ok interesting 🤔 it looks like the watcher stream that listens to lease events timed out twice, and then somehow resumed but gets error events, maybe because after a while the revision number is too old? At the moment, the lib just logs and ignores events of error type, but this probably indicates that instead, it should attempt to reset its internal state when this happens, and restart from scratch by listing leases and subscribing. I can work on modifying this behavior. 
Does this occur often?

**Comment by M-J-Brown** [comment]
I only deployed this yesterday, so it's 1 time out of 1 time so far 😅 I will keep an eye out.

Is how I'm using the Lease in code how you'd expect it to be used?

**Comment by jchapuis** [comment]
> I only deployed this yesterday, so it's 1 time out of 1 time so far 😅 I will keep an eye out.
ok darn. i admit I haven't observed long-running sessions with it yet. but we should be able to make it robust, the kube API supports event watchers. but there might be subtle behavior weirdness sometimes, also with varying implementations   

> Is how I'm using the Lease in code how you'd expect it to be used?
yes sure. the wrapping of a lease in resource means that it will get deleted upon release (if the kube API can be contacted, that is - otherwise it gets recycled after some time, like you observed)

**Comment by M-J-Brown** [comment]
Yeah, happened again last night, so 2 out of 2 💔

**Comment by jchapuis** [comment]
> Yeah, happened again last night, so 2 out of 2 💔

sorry to hear. but at least we know it's part of typical EKS behavior now. Could you try with the latest `v0.3.2` version? I've changed the behavior slightly. It now should re-open the stream in case of this error event. If that still doesn't work, I will consider a bigger change.

**Comment by M-J-Brown** [comment]
That has run successfully all weekend - looking good! Thanks again @jchapuis 👌

**Comment by jchapuis** [comment]
> That has run successfully all weekend - looking good! Thanks again @jchapuis 👌

Great to hear! closing this issue for now then but feel free to let me know if anything else occurs
